// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyfzhxbtnaueqqceowwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5ZnpoeGJ0bmF1ZXFxY2Vvd3dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDI5MzIsImV4cCI6MjA2MjgxODkzMn0.rLfuHdpE_T2OnMiUOVDcU5OzFHD9SqO2w5B3Ryn_y34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);